node{
    stage("init"){
        cleanWs()
        
        checkout scm
        sh 'ls'
    }
    stage("code-Coverage"){
        sh './coco.sh'
    }
    stage("Static code analysis"){
        withSonarQubeEnv('Sonar'){
            sh "sonar-scanner -Dsonar.projectKey=Jenkins_CMake_Gtest -Dsonar.sources=source,include,test"
        }
    }
    stage("build"){
        sh './build.sh'
    }
    stage("test"){
        sh'./test.sh'
    }
}
