node{
    stage("init"){
        cleanWs()
        
        checkout scm
        sh 'ls'
    }
    stage("code-Coverage"){
        sh './coco.sh'
    }
    stage("build"){
        sh './build.sh'
    }
    stage("test"){
        sh'./test.sh'
    }
}
