node{
    stage("init"){
        cleanWs()
        
        checkout scm
        sh 'ls'
    }
    stage("code-Coverage"){
        try{
            sh 'exit 1'  
        }catch (error) {
            currentBuild.result='UNSTABLE'
        }
          
    }
    stage("Extract coverage report"){
        cobertura coberturaReportFile: 'cocov/cobertura.xml'
    }
    stage("Static code analysis"){
        withSonarQubeEnv('Sonar'){
            sh "sonar-scanner -Dsonar.projectKey=Jenkins_Gtest_CMake2 -Dsonar.sources=source,include,test"
        }
    }
    stage("build"){
        sh './build.sh'
    }
    stage("test"){
        sh'./test.sh'
    }
    stage("extract test results"){
        junit allowEmptyResults: true, testResults: 'test/build/*.xml' 
    }
}
